name: DeadLinks Check

on:  
  schedule:
    # - cron: '0 17 * * 3'  # 12AM GMT+7 mỗi thứ Tư  
  repository_dispatch:
    types: [check-link]  
  workflow_dispatch:

jobs:
  check: 
    runs-on: ubuntu-latest
    # timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests PyGithub

      - name: Check dead links
        run: |
          python check_urls.py

  send_email: 
    runs-on: ubuntu-latest
    needs: check  
    steps:
      - name: Download log artifact
        uses: actions/download-artifact@v4
        with:
          name: rclone-log
          path: .

      - name: Read log into variable
        id: read_log
        run: |
          if [ -f rclone_log.txt ]; then
            LOG_CONTENT=$(cat rclone_log.txt)
            echo "LOG_CONTENT<<EOF" >> $GITHUB_ENV
            echo "$LOG_CONTENT" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "LOG_CONTENT=No log file found" >> $GITHUB_ENV
          fi

      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APPWRD }}
          subject: Backup results
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: UIT-Learning-Archive
          body: |
            Backup process completed.
            See attached log for details.

          attachments: rclone_log.txt
