name: Delete auto/md - update branches

on:
  schedule:
    - cron: '0 0 * * 1'   
  workflow_dispatch:

permissions:
  contents: write        

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Delete branch created by update_date workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            repos/${{ github.repository }}/git/refs/heads/auto/update-date 
