name: Delete auto/md - update branches

on:
  schedule:
    - cron: '0 2 * * 6'   
  workflow_dispatch:

permissions:
  contents: write        

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Delete branch created by update_date workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh api repos/${{ github.repository }}/git/ref/heads/auto/update-date --silent >/dev/null 2>&1; then
            gh api \
              --method DELETE \
              repos/${{ github.repository }}/git/refs/heads/auto/update-date
          else
            echo "Branch auto/update-date does not exist. Skipping delete."
          fi
