name: demo

on:  
    schedule:
    #- cron: "15 4,5 * * *"   # <=== Change this value
    workflow_dispatch:
jobs:
    check: 
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check dead links

      #logic for checking dead links