name: Update Markdown Dates

on:
  schedule:
    - cron: '0 2 * * 1'  
  workflow_dispatch:     

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib python-dateutil

      - name: Decode service account key
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service-account.json

      - name: Run update script
        run: python update_script.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update last modified dates in Markdown from Google Drive"
          title: "PR: Update Markdown with latest Google Drive dates"
          body: |
            A pull request automatically created by GitHub Actions to update the last modified date from Google Drive into the Markdown file.
          branch: auto/md-update
          base: main
          delete-branch: true

  assign-reviewer:
    needs: update-dates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              head: context.repo.owner + ":auto/md-update"
            });

            if (pr.data.length > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data[0].number,
                reviewers: ["thu4n"]  
              });
            }
