name: Update Markdown Dates

on:
  schedule:
    - cron: '0 2 * * 1'  # Chạy mỗi thứ Hai lúc 02:00 UTC
  workflow_dispatch:       # Cho phép chạy thủ công

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib python-dateutil

      - name: Decode service account key
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > drive-api-project-452000-10d4b5dc6bcc.json

      - name: Run update script
        run: python update_script.py

      - name: Check if there are any changes
        id: git-check
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate timestamp for branch name
        id: time
        run: echo "ts=auto/md-update-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update last modified dates in Markdown from Google Drive"
          title: "PR: Update Markdown with latest Google Drive dates"
          body: |
            A pull request automatically created by GitHub Actions to update the last modified date from Google Drive into the Markdown file.
          branch: ${{ steps.time.outputs.ts }}
          base: main
          delete-branch: true
          reviewers: thu4n
          assignees: thu4n
